package com.rls.gps.common.web;

import java.util.List;

/**
 * HTTP headers exchanged between Kong and the GPS services.
 *
 * <p>The identity headers are <em>never</em> trusted from a client: the {@code rls_auth} Kong plugin
 * strips whatever the caller sent and re-injects the values it verified against the Id service.
 */
public final class GpsHeaders {

    /** Company (tenant) the caller belongs to. Injected by the gateway. */
    public static final String COMPANY_ID = "X-Company-Id";

    /** Authenticated user. Injected by the gateway. */
    public static final String USER_ID = "X-User-Id";

    /** Company app key the token was issued for. Injected by the gateway. */
    public static final String APP_KEY = "X-App-Key";

    /** Shared secret proving the request really came through Kong. */
    public static final String GATEWAY_TOKEN = "X-Gateway-Token";

    /** Correlation id, generated by Kong's correlation-id plugin or by the first service hit. */
    public static final String CORRELATION_ID = "X-Correlation-Id";

    /** Alternative correlation header some clients send. */
    public static final String REQUEST_ID = "X-Request-Id";

    /** Server secret required by restricted endpoints (company signup), per the original spec. */
    public static final String SERVER_SECRET = "sret";

    /** Headers a client must never be able to set itself. */
    public static final List<String> IDENTITY_HEADERS = List.of(COMPANY_ID, USER_ID, APP_KEY);

    private GpsHeaders() {
    }
}
